export const ConfirmActionType = Object.freeze({
  DELETION: "Deletion",
  APPROVAL: "Approval",
  RESTORE: "Restore",
  RENEWAL: "Renewal",
  CANCEL: "Cancel",
  ORDER: "Order",
  SUSPEND: "Suspend",
  REMOVE: "Remove",
  APPROVE: "Approve",
  DECLINE: "Decline",
  REQUEST: "Request",
  RESET: "Reset",
  CHANGE: "Change",
});

export const ConfirmActionWords = Object.freeze({
  Deletion: "delete",
  Approval: "approve",
  Restore: "restore",
  Renewal: "renewal",
  Cancel: "cancel",
  Order: "cancel this order",
  Suspend: "suspend",
  Remove: "remove",
  Approve: "approve",
  Decline: "decline",
  Request: "request",
  Reset: "reset",
  Change: "change",
});
