export const logs_action = Object.freeze({
  CHANGE_PASSWORD: "Change Password",
  EDITED_ADMIN: "Edited Admin",
  ADMIN_LOGIN: "Admin Login",
  ADMIN_LOGOUT: "Admin Logout",
  EXPORT: "Exported Merchandise Report CSV",
  REMOVE_ROLE: "Remove Role",
  SUSPEND: "Suspend Admin Account",
  RESTORE: "Restore Suspended Admin",
  REQUEST_ROLE: "Requested a Role",
  APPROVE_ROLE: "Approved a Role",
  DECLINE_ROLE: "Decline a Role",
  CREATE_ADMIN: "Create Admin Account",
  APPROVE_ADMIN: "Approved Admin Account",
  DECLINE_ADMIN: "Decline Admin Account",
  CHANGE_ACCESS: "Change Access",
  RESEND_EMAIL: "Resent Email",
  CLEAR_EXPIRED_SESSIONS: "Cleared Expired Sessions",
  INVALIDATE_SESSION: "Invalidated Session",
  INVALIDATE_SESSION_BULK: "Bulk Session Invalidation",
  TRIGGER_CRON: "Triggered Cron Job",
  CANCEL_EXPIRED_ORDERS: "Cancelled Expired Orders",
  REBUILD_DB_INDEXES: "Rebuilt Database Indexes",
  TOGGLE_CHATBOT: "Toggled Chatbot",
  // Orders
  APPROVE_ORDER: "Approved Order",
  CANCEL_ORDER: "Cancelled Order",
  REFUND_ORDER: "Refunded Order",
  // Events
  CREATE_EVENT: "Created Event",
  UPDATE_EVENT: "Updated Event",
  DELETE_EVENT: "Deleted Event",
  ADD_ATTENDEE: "Added Attendee",
  UPDATE_ATTENDEE: "Updated Attendee",
  REMOVE_ATTENDEE: "Removed Attendee",
  EVENT_SETTINGS_UPDATE: "Updated Event Settings",
  // Raffle
  RAFFLE_DRAW: "Raffle Draw",
  RAFFLE_RESET: "Raffle Reset",
  RAFFLE_UNDO: "Raffle Undo",
  // Promo
  CREATE_PROMO: "Created Promo",
  UPDATE_PROMO: "Updated Promo",
  DELETE_PROMO: "Deleted Promo",
  // Recruitment
  CREATE_POSITION: "Created Recruitment Position",
  UPDATE_POSITION: "Updated Recruitment Position",
  DELETE_POSITION: "Deleted Recruitment Position",
  TOGGLE_HIRING: "Toggled Hiring Status",
  APPROVE_APPLICANT: "Approved Applicant",
  REJECT_APPLICANT: "Rejected Applicant",
  VERIFY_APPLICANT: "Verified Applicant",
  APPLICATION_STATUS_UPDATE: "Updated Application Status",
  CREATE_INTERVIEW: "Created Interview",
  UPDATE_INTERVIEW: "Updated Interview",
  CANCEL_INTERVIEW: "Cancelled Interview",
  DELETE_APPLICATION: "Deleted Application",
  CLEAR_REJECTED: "Cleared Rejected Applicants",
  // Certificates
  CREATE_TEMPLATE: "Created Certificate Template",
  UPDATE_TEMPLATE: "Updated Certificate Template",
  DELETE_TEMPLATE: "Deleted Certificate Template",
  GENERATE_CERTIFICATE: "Generated Certificates",
  UPDATE_ELIGIBILITY: "Updated Certificate Eligibility",
  IMPORT_CERTIFICATE: "Imported Certificate Data",
  // Students
  UPDATE_STUDENT: "Updated Student",
  DELETE_STUDENT: "Deleted Student",
  BACKFILL_CREATED_AT: "Backfilled Created At (Migration)",
  UPDATE_STUDENT_YEAR: "Updated Student Years",
  DECREMENT_STUDENT_YEAR: "Decrement Student Years",
  // Membership
  APPROVE_MEMBERSHIP: "Approved Membership",
  REVOKE_MEMBERSHIP: "Revoked Memberships",
  CHANGE_MEMBER_PRICE: "Changed Membership Price",
  // Reports
  EXPORT_REPORT: "Exported Report",
  // Contributions
  CREATE_CONTRIBUTION: "Created Contribution",
  UPDATE_CONTRIBUTION: "Updated Contribution",
  DELETE_CONTRIBUTION: "Deleted Contribution",
  SYNC_DEVELOPER_CONTRIBUTIONS: "Synced Developer Contributions",
  UPDATE_GITHUB_USERNAME: "Updated GitHub Username",
  // Automation Jobs
  CREATE_AUTOMATION_JOB: "Created Automation Job",
  UPDATE_AUTOMATION_JOB: "Updated Automation Job",
  DELETE_AUTOMATION_JOB: "Deleted Automation Job",
  RUN_AUTOMATION_JOB: "Ran Automation Job",
});
