export const logs_action = Object.freeze({
  CHANGE_PASSWORD: "Change Password",
  EDITED_ADMIN: "Edited Admin",
  ADMIN_LOGIN: "Admin Login",
  ADMIN_LOGOUT: "Admin Logout",
  EXPORT: "Exported Merchandise Report CSV",
  REMOVE_ROLE: "Remove Role",
  SUSPEND: "Suspend Admin Account",
  RESTORE: "Restore Suspended Admin",
  REQUEST_ROLE: "Requested a Role",
  APPROVE_ROLE: "Approved a Role",
  DECLINE_ROLE: "Decline a Role",
  CREATE_ADMIN: "Create Admin Account",
  APPROVE_ADMIN: "Approved Admin Account",
  DECLINE_ADMIN: "Decline Admin Account",
  CHANGE_ACCESS: "Change Access",
  RESEND_EMAIL: "Resent Email",
  CLEAR_EXPIRED_SESSIONS: "Cleared Expired Sessions",
  INVALIDATE_SESSION: "Invalidated Session",
  INVALIDATE_SESSION_BULK: "Bulk Session Invalidation",
  TRIGGER_CRON: "Triggered Cron Job",
  CANCEL_EXPIRED_ORDERS: "Cancelled Expired Orders",
  REBUILD_DB_INDEXES: "Rebuilt Database Indexes",
});
